### ISSUE TITLE
Question: how to create the input file as "jawiki-all-titles" file in "Example 1: Construction"

### ISSUE THREAD

**Issue by zhirshya** [kampersanda/xcdat#1]
Hello, excuse me for asking questions here by opening an issue, being this is not an issue.

How to create the input dataset for building a dictionary using your library? For instance, "jawiki-all-titles" file in "Example 1: Construction".
I can only think of that the entire raw original words must be specified as the input, but exactly how to organize input words in the input file? For example, place one word in a line?
Since I saw std::sort is used in your example code "Sample Usage", I think ordering words lexicographically in input file is better but not required, am I right?

I want to use your library to create a dictionary file for a traditional Mongolian IME.
How did you make the "jawiki-all-titles" file?

**Comment by kampersanda** [comment]
The input file has to consist of (lexicographically) sorted words, separated by lines.

**Comment by zhirshya** [comment]
Thank you very much for your reply.
I think maybe your library doesn't support unicode traditional Mongolian (1800~1840) text.
Does it support unicode strings?

I created unicode traditional Mongolian text file with about 700 words, each on its own line.
I sorted and removed duplicates using

`$sort mgtxt-orig | uniq -u > mgtxt-srtunq`

```
$file mgtxt-srtunq
mgtxt-srtunq: UTF-8 Unicode text
```

then executed
`$xcdat build 1 mgtxt-srtunq`

and I got
`The input data is not in lexicographical order.`

system locale is
```$locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Could you give hints about causes of the problem?

Maybe the sort command I used didn't sort lexicographically, I'll look at lexicographical order for traditional Mongolian later, it'll take some time.

**Comment by kampersanda** [comment]
Please try the following sort command:
```
$ env LC_ALL=C sort mgtxt-orig
```

**Comment by zhirshya** [comment]
Thank you very much, your command worked.
